---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/launch-stage: BETA
  generation: 4
  labels:
    cloud.googleapis.com/location: $REGION
  name: $SERVICE_NAME
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "$minScale"
        autoscaling.knative.dev/maxScale: "$maxScale"
        # run.googleapis.com/cloudsql-instances: $DB_NAME1,$DB_NAME2,$DB_NAME3
        run.googleapis.com/sandbox: gvisor
    spec:
      containerConcurrency: "$containerConcurrency"
      serviceAccountName: $SERVICE_ACCOUNT
      containers:
        - image: $IMAGE
          ports:
            - containerPort: 3000
              name: http1
          resources:
            limits:
              cpu: $CPU
              memory: $MEMORY
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
