name: Deploy to Cloud Run

on:
  push:
    branches:
      - master
env:
  REGISTRY_BASE: us-central1-docker.pkg.dev/darkiink

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
          token_format: access_token

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          provenance: false
          tags: |
            ${{ env.REGISTRY_BASE }}/cloud-run-source-deploy/darkiink:${{ github.sha }}

  deploy:
    name: Deploy
    needs: ["build"]
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Deploy
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          metadata: ./metadata.yaml
          region: us-central1
